# NN Module

The torch.nn module of Pytorch is a core library that provides a wide array of classes and functions designed to help developers build neural networks efficiently and effectively.
It offers us pre-built layers, loss functions, activation functions, and other utilities.

In [2]:
import torch
import torch.nn as nn

class MyModel(nn.Module):

    def __init__(self, num_features):
        super().__init__()

        self.linear=nn.Linear(num_features,1)
        self.sigmoid=nn.Sigmoid()
    
    def forward(self, features):
        out=self.linear(features)
        out=self.sigmoid(out)
        
        return out

In [3]:
## create dataset
features=torch.rand(10,5)
## create model
model=MyModel(features.shape[1])
## call model for prediction
model(features)

tensor([[0.5157],
        [0.5297],
        [0.5648],
        [0.5606],
        [0.5352],
        [0.6106],
        [0.5213],
        [0.5792],
        [0.5741],
        [0.4862]], grad_fn=<SigmoidBackward0>)

In [4]:
model.linear.weight

Parameter containing:
tensor([[ 0.3301,  0.0211, -0.4249, -0.1582, -0.1176]], requires_grad=True)

In [5]:
!pip install torchinfo

In [6]:
from torchinfo import summary

In [7]:
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
MyModel                                  [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [10]:
class MyModel2(nn.Module):

    def __init__(self, num_features):

        super().__init__()
        self.linear1=nn.Linear(num_features,3)
        self.relu=nn.ReLU()
        self.linear2=nn.Linear(3,1)
        self.sigmoid=nn.Sigmoid()
    
    def forward(self,features):
        out=self.linear1(features)
        out=self.relu(out)
        out=self.linear2(out)
        out=self.sigmoid(out)

        return out

In [11]:
## create dataset
features=torch.rand(10,5)

## create model
model=MyModel2(features.shape[1])

## call model
model(features)

tensor([[0.5980],
        [0.5986],
        [0.5952],
        [0.5958],
        [0.5982],
        [0.5953],
        [0.5973],
        [0.5971],
        [0.5962],
        [0.5971]], grad_fn=<SigmoidBackward0>)

In [12]:
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
MyModel2                                 [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [13]:
class MyModel3(nn.Module):

    def __init__(self, num_features):

        super().__init__()
        self.network=nn.Sequential(linear1=nn.Linear(num_features,3),
        relu=nn.ReLU(),
        linear2=nn.Linear(3,1),
        sigmoid=nn.Sigmoid())
    
    def forward(self,features):
        out=self.network(features)

        return out

In [14]:
## create dataset
features=torch.rand(10,5)

## create model
model=MyModel2(features.shape[1])

## call model
model(features)

tensor([[0.3614],
        [0.3803],
        [0.3650],
        [0.3521],
        [0.3639],
        [0.3943],
        [0.3701],
        [0.3533],
        [0.3442],
        [0.3844]], grad_fn=<SigmoidBackward0>)

In [15]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler

In [16]:
df=pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")
df.head()

id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [17]:
df.shape

(569, 33)

In [18]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)

In [19]:
df.head()

diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0         M        17.99  ...          0.4601                  0.11890
1         M        20.57  ...          0.2750                  0.08902
2         M        19.69  ...          0.3613                  0.08758
3         M        11.42  ...          0.6638                  0.17300
4         M        20.29  ...          0.2364                  0.07678

[5 rows x 31 columns]

In [20]:
X_train, X_test, y_train, y_test= train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

In [21]:
## Scaling

scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [22]:
X_train

array([[ 0.20795426,  1.0391535 ,  0.24425827, ...,  0.68078375,
         0.63514662,  0.26800703],
       [ 0.63763251,  0.30536053,  0.64111679, ...,  0.63411371,
         0.29459951, -0.13364967],
       [ 1.32396422, -0.40117078,  1.34292976, ...,  1.83097446,
         1.38185084,  0.42279456],
       ...,
       [ 0.75874988,  0.18949848,  0.64947171, ..., -0.43372695,
         2.75341213, -0.45960735],
       [-0.3024689 ,  0.64840307, -0.39865253, ..., -1.6096765 ,
        -0.96761179, -1.46516138],
       [ 1.50275652,  1.61392013,  1.518383  , ...,  0.93822173,
         1.18345871,  1.57805187]], shape=(455, 30))

In [23]:
y_train

65     M
328    M
45     M
354    B
531    B
      ..
526    B
100    M
489    M
178    B
33     M
Name: diagnosis, Length: 455, dtype: object

In [24]:
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.transform(y_test)

In [25]:
y_train

array([1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,

In [38]:
X_train_tensor=torch.from_numpy(X_train).float()
X_test_tensor=torch.from_numpy(X_test).float()
y_train_tensor=torch.from_numpy(y_train).float()
y_test_tensor=torch.from_numpy(y_test).float()

In [27]:
X_train_tensor.shape

torch.Size([455, 30])

In [28]:
y_train_tensor.shape

torch.Size([455])

In [ ]:
class MySimpleNN(nn.Module):
    
    def __init__(self, num_features):
        super().__init__()
        self.linear=nn.Linear(num_features,1)
        self.sigmoid=nn.Sigmoid()

    def forward(self, features):
        out=self.linear(features)
        out=self.sigmoid(out)

        return out
    

In [31]:
learning_rate=0.1
epochs=25

In [42]:
loss_function=nn.BCELoss()

In [43]:
type(loss_function)

torch.nn.modules.loss.BCELoss

# torch.optim
torch.optim is a module in PyTorch that provides a variety of optimization algorithms used to update the parameters of you model during training. it has optimizers like SGD, Adam, RMSprop, and more.

The model.parameters() method in PyTorch retrieves an iterator over all the trainable parameters (weights and biases) in a model.

In [48]:
# create model

model=MySimpleNN(X_train_tensor.shape[1])

#define optimizer
optimizer=torch.optim.SGD(model.parameters(),learning_rate)

## in loop
for epoch in range(epochs):
    # forward pass
    y_pred=model(X_train_tensor)

    ## loss calculate
    loss=loss_function(y_pred,y_train_tensor.view(-1,1))

    #zero gradients
    optimizer.zero_grad()

    ## bckward pass
    loss.backward()

    ##parameters update
    optimizer.step()

    ## print loss in every epoch
    print(f'Epoch: {epoch+1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.7292588353157043
Epoch: 2, Loss: 0.5686249136924744
Epoch: 3, Loss: 0.47795552015304565
Epoch: 4, Loss: 0.4191499948501587
Epoch: 5, Loss: 0.37751340866088867
Epoch: 6, Loss: 0.3462715148925781
Epoch: 7, Loss: 0.3218357264995575
Epoch: 8, Loss: 0.30211764574050903
Epoch: 9, Loss: 0.2858150601387024
Epoch: 10, Loss: 0.2720720171928406
Epoch: 11, Loss: 0.260301411151886
Epoch: 12, Loss: 0.2500864863395691
Epoch: 13, Loss: 0.24112260341644287
Epoch: 14, Loss: 0.23318156599998474
Epoch: 15, Loss: 0.22608870267868042
Epoch: 16, Loss: 0.21970798075199127
Epoch: 17, Loss: 0.21393167972564697
Epoch: 18, Loss: 0.2086731195449829
Epoch: 19, Loss: 0.20386196672916412
Epoch: 20, Loss: 0.19944031536579132
Epoch: 21, Loss: 0.19536006450653076
Epoch: 22, Loss: 0.1915808916091919
Epoch: 23, Loss: 0.18806873261928558
Epoch: 24, Loss: 0.18479451537132263
Epoch: 25, Loss: 0.1817334145307541


In [40]:
model.linear.weight

Parameter containing:
tensor([[-0.0613,  0.0186,  0.0801, -0.1407,  0.1399, -0.0022, -0.0982,  0.0488,
         -0.0581,  0.0215,  0.1511,  0.0704, -0.0996,  0.1088, -0.1052, -0.1230,
          0.0985,  0.1137, -0.0513, -0.1145,  0.1178, -0.0442, -0.0711, -0.1797,
         -0.1386,  0.1607,  0.0781, -0.0155,  0.0055, -0.0414]],
       requires_grad=True)

In [49]:
#Evaluation

with torch.no_grad():
    y_pred=model.forward(X_test_tensor)
    y_pred=(y_pred>0.5).float()
    accuracy=(y_pred == y_test_tensor).float().mean()

    print(f'Accuracy of the model: {accuracy.item()}')

Accuracy of the model: 0.5301631093025208
