In [15]:
import torch
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [16]:
df=pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [17]:
df.shape

(569, 33)

In [18]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)

In [19]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [20]:
X_train, X_test, y_train, y_test= train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

In [21]:
## Scaling

scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [22]:
X_train

array([[-1.3932281 ,  0.55484937, -1.38022741, ..., -1.3933171 ,
        -0.8825609 ,  0.40767994],
       [ 0.92400996,  0.64568702,  0.86301451, ...,  1.27629478,
         0.51339575, -0.50655618],
       [-1.41225841,  0.61540781, -1.41224282, ..., -1.3933171 ,
        -0.78451156, -0.60546804],
       ...,
       [-0.63707047, -0.24638529, -0.68973289, ..., -0.8166216 ,
        -0.20286296, -0.59708568],
       [ 2.71404886,  1.78698058,  2.67577896, ...,  2.21736541,
         0.32560634,  0.11206203],
       [-0.24159676, -0.53054409, -0.30727853, ..., -0.29401061,
        -0.66651999, -0.47693851]], shape=(455, 30))

In [23]:
y_train

412    B
264    M
553    B
342    B
216    B
      ..
564    M
25     M
52     B
236    M
224    B
Name: diagnosis, Length: 455, dtype: object

In [24]:
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.transform(y_test)

In [25]:
y_train

array([0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0,

In [26]:
X_train_tensor=torch.from_numpy(X_train)
X_test_tensor=torch.from_numpy(X_test)
y_train_tensor=torch.from_numpy(y_train)
y_test_tensor=torch.from_numpy(y_test)

In [28]:
X_train_tensor.shape

torch.Size([455, 30])

In [29]:
y_train_tensor.shape

torch.Size([455])

In [38]:
class MySimpleNN():
    
    def __init__(self,X):

        self.weights=torch.rand(X.shape[1],1,dtype=torch.float64,requires_grad=True)
        self.bias=torch.zeros(1,dtype=torch.float64,requires_grad=True)
        
    def forward(self,X):
        z=torch.matmul(X,self.weights)+self.bias
        y_pred=torch.sigmoid(z)
        return y_pred
    
    def loss_function(self, y_pred, y):
        epsilon=1e-7
        y_pred=torch.clamp(y_pred,epsilon,1-epsilon)

        loss=-(y_train_tensor*torch.log(y_pred) + (1-y_train_tensor)*torch.log(1-y_pred)).mean()
        return loss

In [39]:
learning_rate=0.1
epochs=25

In [40]:
# create model

model=MySimpleNN(X_train_tensor)

## in loop
for epoch in range(epochs):
    # forward pass
    y_pred=model.forward(X_train_tensor)

    ## loss calculate
    loss=model.loss_function(y_pred,y_train_tensor)

    ## bckward pass
    loss.backward()

    ##parameters update
    with torch.no_grad():
        model.weights -= learning_rate* model.weights.grad
        model.bias -= learning_rate*model.bias.grad

    #zero gradients
    model.weights.grad.zero_()
    model.bias.grad.zero_()

    ## print loss in every epoch
    print(f'Epoch: {epoch+1}, Loss: {loss.item()}')

Epoch: 1, Loss: 4.105683754453881
Epoch: 2, Loss: 3.9925498056857367
Epoch: 3, Loss: 3.8714230771589966
Epoch: 4, Loss: 3.742163421711877
Epoch: 5, Loss: 3.60593190464195
Epoch: 6, Loss: 3.4675807250229096
Epoch: 7, Loss: 3.326700454455416
Epoch: 8, Loss: 3.1797181452433105
Epoch: 9, Loss: 3.025025967217604
Epoch: 10, Loss: 2.869204708163538
Epoch: 11, Loss: 2.7078158914766144
Epoch: 12, Loss: 2.535043471447257
Epoch: 13, Loss: 2.356585978976048
Epoch: 14, Loss: 2.1793245850707135
Epoch: 15, Loss: 2.003805873183731
Epoch: 16, Loss: 1.8305846866185793
Epoch: 17, Loss: 1.6642863716006333
Epoch: 18, Loss: 1.503940749133835
Epoch: 19, Loss: 1.3559300406058503
Epoch: 20, Loss: 1.22077313467919
Epoch: 21, Loss: 1.104794407199276
Epoch: 22, Loss: 1.009804207965115
Epoch: 23, Loss: 0.9359461112218435
Epoch: 24, Loss: 0.8814915927187726
Epoch: 25, Loss: 0.8432174003280302


In [41]:
model.weights

tensor([[ 0.0910],
        [ 0.1565],
        [ 0.1528],
        [ 0.2987],
        [-0.0555],
        [ 0.2971],
        [ 0.0315],
        [-0.2591],
        [-0.1571],
        [-0.1089],
        [-0.1643],
        [ 0.0646],
        [-0.4723],
        [ 0.1822],
        [ 0.1542],
        [ 0.4857],
        [ 0.1585],
        [ 0.2486],
        [ 0.6777],
        [-0.1037],
        [-0.1253],
        [-0.2597],
        [ 0.2549],
        [ 0.1994],
        [ 0.4977],
        [-0.4289],
        [-0.4941],
        [ 0.1389],
        [ 0.4616],
        [-0.1422]], dtype=torch.float64, requires_grad=True)

In [42]:
#Evaluation

with torch.no_grad():
    y_pred=model.forward(X_test_tensor)
    y_pred=(y_pred>0.5).float()
    accuracy=(y_pred == y_test_tensor).float().mean()

    print(f'Accuracy of the model: {accuracy.item()}')

Accuracy of the model: 0.5207756161689758
