In [2]:
import torch

In [3]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    print("Using GPU:", torch.cuda.get_device_name(0))
else:
    device = torch.device("cpu")
    print("Using CPU")

Using CPU


In [4]:
a=torch.empty(2,3)

In [5]:
type(a)

torch.Tensor

In [6]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
torch.rand(2,3)

tensor([[0.6381, 0.1169, 0.9725],
        [0.7993, 0.1325, 0.2385]])

In [9]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [10]:
torch.rand(2,3)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

In [11]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [12]:
torch.full((3,5),10)

tensor([[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]])

In [13]:
x=torch.tensor([[1,2,3,4],[1,2,3,4]])

In [14]:
x.shape

torch.Size([2, 4])

In [15]:
torch.empty_like(x)

tensor([[    139656260435520,     139656260435520,                   0,
                           0],
        [4593433446801473536, 7310593858020254331, 3616445622929465956,
         6067811242765987125]])

In [16]:
torch.zeros_like(x)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]])

In [17]:
torch.ones_like(x)

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1]])

In [ ]:
torch.rand_like(x)
##this code will not work, as the tensor x is of integer type and rand_like generates float values

RuntimeError: "check_uniform_bounds" not implemented for 'Long'

In [19]:
x.dtype

torch.int64

In [20]:
torch.tensor([1,2,3,4], dtype=torch.float64)

tensor([1., 2., 3., 4.], dtype=torch.float64)

In [27]:
x=x.to(torch.float32)

In [28]:
x

tensor([[1., 2., 3., 4.],
        [1., 2., 3., 4.]])

In [29]:
torch.rand_like(x)

tensor([[0.7118, 0.7876, 0.4183, 0.9014],
        [0.9969, 0.7565, 0.2239, 0.3023]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


In [31]:
# Mathematical Operations

x=torch.rand(2,2)
x

tensor([[0.1784, 0.8238],
        [0.5557, 0.9770]])

In [32]:
x+2

tensor([[2.1784, 2.8238],
        [2.5557, 2.9770]])

In [33]:
x-2

tensor([[-1.8216, -1.1762],
        [-1.4443, -1.0230]])

In [34]:
x*2

tensor([[0.3568, 1.6477],
        [1.1115, 1.9540]])

In [35]:
x/2

tensor([[0.0892, 0.4119],
        [0.2779, 0.4885]])

In [36]:
(x*100)//3

tensor([[ 5., 27.],
        [18., 32.]])

In [37]:
((x*100)//3)%2

tensor([[1., 1.],
        [0., 0.]])

Similarly these operations can also be performed on two tensors

In [38]:
c=torch.tensor([-1,2,-3,4])

In [39]:
torch.abs(c)

tensor([1, 2, 3, 4])

In [40]:
torch.neg(c)

tensor([ 1, -2,  3, -4])

In [41]:
## torch.round(), torch.floor(), torch.ceil() can also be used for rounding off the decimal values.

In [ ]:
##torch.clamp() can be used to limit the values in a tensor to a specified range.

In [46]:
e=torch.randint(size=(2,3), low=0, high=10,dtype=torch.float32)
e

tensor([[7., 0., 0.],
        [9., 5., 7.]])

In [47]:
torch.sum(e)

tensor(28.)

In [48]:
torch.sum(e, dim=0)  #column wise sum

tensor([16.,  5.,  7.])

In [49]:
torch.sum(e, dim=1)  #row wise sum

tensor([ 7., 21.])

In [ ]:
torch.mean(e) #can be calculated only for float tensors

# can be calculated for columns or rows also

tensor(4.6667)

In [52]:
'''
torch.std(e) #standard deviation
torch.std(e, dim=0) #column wise standard deviation
torch.std(e, dim=1) #row wise standard deviation

torch.var(e) #variance

torch.argmax(e) #index of maximum value in the tensor
torch.argmin(e) #index of minimum value in the tensor

'''

'\ntorch.std(e) #standard deviation\ntorch.std(e, dim=0) #column wise standard deviation\ntorch.std(e, dim=1) #row wise standard deviation\n\ntorch.var(e) #variance\n\ntorch.argmax(e) #index of maximum value in the tensor\ntorch.argmin(e) #index of minimum value in the tensor\n\n'

In [55]:
f=torch.randint(size=(3,3), low=0, high=10)
g=torch.randint(size=(3,3), low=0, high=10)

In [56]:
torch.matmul(f,g)

tensor([[129, 104, 114],
        [103,  59,  77],
        [188, 124, 162]])

In [60]:
v1=torch.tensor([1,2,3])
v2=torch.tensor([4,5,6])

torch.dot(v1,v2)

tensor(32)

In [61]:
torch.transpose(f,0,1)

tensor([[3, 0, 5],
        [9, 5, 9],
        [4, 7, 9]])

In [67]:
h=torch.rand(3,3)
torch.det(h)  #determinant of a square matrix

tensor(0.0006)

In [70]:
torch.inverse(f.to(torch.float32))  #inverse of a square matrix

tensor([[-0.1118, -0.2795,  0.2671],
        [ 0.2174,  0.0435, -0.1304],
        [-0.1553,  0.1118,  0.0932]])

In [74]:
## Inplace operations

torch.relu(h)

## This stores the values in a new tensor, but pytorch provides inplace operations too, just add an underscore(_) at the end of a function name. for e.g

h.relu_()

tensor([[0.1157, 0.6574, 0.3451],
        [0.0453, 0.9798, 0.5548],
        [0.6868, 0.4920, 0.0748]])

In [ ]:
h #the value of h has been changed as relu as been applied inplace

tensor([[0.1157, 0.6574, 0.3451],
        [0.0453, 0.9798, 0.5548],
        [0.6868, 0.4920, 0.0748]])

In [82]:
a=torch.rand(3,2)

In [83]:
a

tensor([[0.9141, 0.7668],
        [0.1659, 0.4393],
        [0.2243, 0.8935]])

In [84]:
b=a

In [85]:
b

tensor([[0.9141, 0.7668],
        [0.1659, 0.4393],
        [0.2243, 0.8935]])

In [86]:
a[0][0]=0

In [87]:
a

tensor([[0.0000, 0.7668],
        [0.1659, 0.4393],
        [0.2243, 0.8935]])

In [ ]:
b ##b also gets changed because both a and b point to the same memory location. To avoid this we can use clone() function

tensor([[0.0000, 0.7668],
        [0.1659, 0.4393],
        [0.2243, 0.8935]])

In [90]:
b=a.clone()

In [91]:
b

tensor([[0.0000, 0.7668],
        [0.1659, 0.4393],
        [0.2243, 0.8935]])

In [92]:
a[0][0]=9

In [93]:
a

tensor([[9.0000, 0.7668],
        [0.1659, 0.4393],
        [0.2243, 0.8935]])

In [94]:
b

tensor([[0.0000, 0.7668],
        [0.1659, 0.4393],
        [0.2243, 0.8935]])

# Tensor Operations on GPU

In [98]:
torch.cuda.is_available()

False

In [99]:
device=torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [100]:
#creating a new tensor on GPU
x=torch.rand(3,3, device=device)

In [101]:
x

tensor([[0.0497, 0.1780, 0.3011],
        [0.1893, 0.9186, 0.2131],
        [0.3957, 0.6017, 0.4234]])

In [103]:
#moving a tensor to GPU
b=x.to(device)

# Testing the results of CPU vs GPU

In [104]:
import torch
import time

size=10000

matrix_cpu1=torch.randn(size, size)
matrix_cpu2=torch.randn(size, size)

start_time=time.time()
matrix_cpu3=torch.matmul(matrix_cpu1, matrix_cpu2)
end_time=time.time()-start_time

matrix_gpu1=matrix_cpu1.to(device)
matrix_gpu2=matrix_cpu2.to(device)

start_time=time.time()
matrix_gpu3=torch.matmul(matrix_gpu1, matrix_gpu2)
end_time=time.time()-start_time
print("Time taken for CPU: ", end_time)
print("Time taken for GPU: ", end_time)

KeyboardInterrupt: 

# Reshaping Tensors

In [3]:
a= torch.ones(4,4)

In [4]:
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [5]:
#reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [6]:
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [7]:
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
b=torch.rand(2,3,4)
b

tensor([[[0.9324, 0.9468, 0.3545, 0.4846],
         [0.9529, 0.0789, 0.0095, 0.3111],
         [0.6530, 0.8689, 0.4699, 0.9534]],

        [[0.8174, 0.7747, 0.1792, 0.3187],
         [0.5354, 0.0101, 0.1807, 0.8744],
         [0.5574, 0.9976, 0.8544, 0.7435]]])

In [11]:
# permute
b.permute(2,0,1).shape  #changes the order of dimensions

torch.Size([4, 2, 3])

In [12]:
#unsqueeze
c=torch.rand(266,266,3)
c.unsqueeze(0).shape

torch.Size([1, 266, 266, 3])

In [13]:
#squeeze
c.unsqueeze(0).squeeze(0).shape

torch.Size([266, 266, 3])

# Numpy to Torch

In [14]:
import numpy as np

In [15]:
a=torch.tensor([1,2,3])

In [16]:
a

tensor([1, 2, 3])

In [17]:
b=a.numpy()

In [18]:
b

array([1, 2, 3])

In [19]:
type(b)

numpy.ndarray